### ISSUE TITLE
Run a node script as a command

### ISSUE THREAD

**Issue by ccgview** [danistefanovic/hooka#29]
Is it possible to make this be able to run a node script as a command when i try i get and unhandled promise error.

**Comment by danistefanovic** [comment]
Hi @ccgview! Any arbitrary command can be executed. Here is a simple example with a node script:

### webhooks.json
```
[
    {
        "method": "GET",
        "path": "/hello-node",
        "command": "node hello-node.js"
    }
]
```

### hello-node.js
```
console.log("hello from node");
```

### How to start
1. Start hooka in the same directory as the webhook.json file
```
$ hooka
```

2. Open http://localhost:3000/hello-node in your browser

3. Output:
```sh
$ hooka
Hooka webhook server is running on port 3000
1505391968034 GET /hello-node
1505391968034 | hello from node
1505391968034 exited with code 0
```

I hope the above is useful to you. If you require any further information, let me know.
